[tool.poetry]
name = "hacksquad-bot"
version = "0.1.0"
description = ""
authors = ["Arpan Pandey <arpanpandey.aps@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "^2.0.1"
jishaku = "^2.5.1"
aiohttp = "^3.8.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
python-dotenv = "^0.21.0"
pre-commit = "^2.20.0"
black = "^22.8.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile=black